<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_67892a1b3c4d5e6f',
    'title' => __('LinkCards Module', 'modularity-link-cards'),
    'fields' => array(
        0 => array(
            'key' => 'field_67892a1b3c4d5e70',
            'label' => __('Columns', 'modularity-link-cards'),
            'name' => 'columns',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('Number of columns in the grid.', 'modularity-link-cards'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                2 => __('2 columns', 'modularity-link-cards'),
                3 => __('3 columns', 'modularity-link-cards'),
                4 => __('4 columns', 'modularity-link-cards'),
            ),
            'default_value' => 2,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
        1 => array(
            'key' => 'field_67892a1b3c4d5e71',
            'label' => __('Cards', 'modularity-link-cards'),
            'name' => 'cards',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Add link cards to display.', 'modularity-link-cards'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_67892a1b3c4d5e72',
            'button_label' => __('Add Card', 'modularity-link-cards'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_67892a1b3c4d5e72',
                    'label' => __('Title', 'modularity-link-cards'),
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_67892a1b3c4d5e71',
                ),
                1 => array(
                    'key' => 'field_67892a1b3c4d5e73',
                    'label' => __('Description', 'modularity-link-cards'),
                    'name' => 'description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_67892a1b3c4d5e71',
                ),
                2 => array(
                    'key' => 'field_67892a1b3c4d5e74',
                    'label' => __('Link', 'modularity-link-cards'),
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'allow_in_bindings' => 1,
                    'parent_repeater' => 'field_67892a1b3c4d5e71',
                ),
                3 => array(
                    'key' => 'field_67892a1b3c4d5e75',
                    'label' => __('Icon', 'modularity-link-cards'),
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => __('Select an icon for the card.', 'modularity-link-cards'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_67892a1b3c4d5e71',
                ),
                4 => array(
                    'key' => 'field_67892a1b3c4d5e76',
                    'label' => __('Icon Background Color', 'modularity-link-cards'),
                    'name' => 'icon_background_color',
                    'aria-label' => '',
                    'type' => 'color_picker',
                    'instructions' => __('Background color for the icon.', 'modularity-link-cards'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '#7B5B3C',
                    'enable_opacity' => 0,
                    'return_format' => 'string',
                    'custom_palette_source' => '',
                    'palette_colors' => '',
                    'show_color_wheel' => true,
                    'parent_repeater' => 'field_67892a1b3c4d5e71',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-link-cards',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/link-cards',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));

}